FROM node

# Create app directory
WORKDIR /usr/next-altin

# Install NEXT.js dependencies
COPY package.json /usr/next-altin/

# Build NEXT.js project
RUN npm install

COPY . /usr/next-altin/

# Build NEXT.js project
RUN npm run build

# Copy NEXT.js build artifacht to working directory
COPY . /usr/next-altin/

# Expose port 3000
EXPOSE 3000

# Run container with this command
CMD [ "npm", "run", "start" ]